services:
  processamento:
    image: briscese/processamento:latest
    build:
      context: ../processamento # Caminho para a pasta do serviço processamento
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.12
    depends_on:
      - controller-cadastro-autenticacao
    volumes:
      - ../processamento/src:/app/src # Se habilitar, certifique-se que o WORKDIR e CMD no Dockerfile ainda funcionam
      - ../processamento/mnt/data:/app/mnt/data # Se habilitar, certifique-se que o WORKDIR e CMD no Dockerfile ainda funcionam


  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Havia um erro de digitação aqui: POSTGRES_postgres, deveria ser POSTGRES_DB
      - POSTGRES_DB=test_postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.2

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doxito007@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "3050:80"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.3
    depends_on:
      - postgres

  pre-processamento:
    image: briscese/pre-processamento:latest
    build:
      context: ../pre-processamento # Caminho para a pasta do serviço pre-processamento
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.10
    depends_on:
      - controller-cadastro-autenticacao
    volumes:
      - ../pre-processamento/src:/app/src
      - ../processamento/mnt/data:/app/mnt/data

  banco-de-dados:
    image: briscese/banco-de-dados:latest
    build:
      # CORRIGIDO: O contexto deve apontar para a pasta do serviço banco-de-dados
      context: ../banco-de-dados 
      dockerfile: Dockerfile # Assegure-se que o Dockerfile está em ../banco-de-dados/Dockerfile
    ports:
      - "5003:5003"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.11
    depends_on:
      - controller-cadastro-autenticacao
    env_file:
      # CORRIGIDO (Exemplo): Se o .env está na pasta do serviço banco-de-dados
      - ../banco-de-dados/.env 
      # Se o .env estiver na raiz do projeto API (C:\6 Semestre Fatec\API\.env), use:
      # - ../.env 
      # Se estiver na mesma pasta que o docker-compose-dev.yaml (C:\6 Semestre Fatec\API\processamento\.env)
      # e for para o serviço banco-de-dados (o que seria incomum), então seria apenas:
      # - .env

  controller-cadastro-autenticacao:
    image: briscese/nc-controller-cadastro-autenticacao:latest
    ports:
      - "3000:3000"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.4
    depends_on:
      - pgadmin
      - postgres

volumes:
  postgres-data:


networks:
  rede_microsservicos:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16